### ISSUE TITLE
Add media queries

### ISSUE THREAD

**Issue by tinchox5** [zumerlab/orbit#7]
Try to add some media queries to change `--o-force` CSS variable.

Original code

```css
.gravity-spot {
  container-name: gravityspot;
  /* Reset to defaults everytime gravity-spot is used */
  --o-force: 500px;
  --o-from: 0deg;
  --o-range: 360deg;
  --o-ellipse-x: 1;
  --o-ellipse-y: 1;
  --o-fit-range: 0;
  --o-direction: 1;
  --o-size-ratio: 1;
  --o-initial-orbit: 0;
  width: 0;
  aspect-ratio: 1;
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  border: none; 
}
```
